### ISSUE TITLE
edr.GetRecords() method is missing. please fix the issue. This code example is from home page of nuget file

### ISSUE THREAD

**Issue by darshana2000** [MarkPflug/Sylvan.Data.Excel#119]
using Sylvan.Data;
using Sylvan.Data.Excel;

using var edr = ExcelDataReader.Create("data.xlsx");
foreach (MyRecord item in edr.GetRecords<MyRecord>())
{
    Console.WriteLine($"{item.Name} {item.Quantity}");
}

class MyRecord
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int? Quantity { get; set; }
    public DateTime Date { get; set; }
}

This code sample is not working. Please check.

edr.GetRecords method is not available.

**Comment by darshana2000** [comment]
Thank you the response,

Yes I tried with nuget.

But i am getting this error now. when reading the excel file.

  HResult=0x80070057
  Message=An item with the same key has already been added. Key: Rated PG
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Sylvan.Data.CompiledDataBinder`1..ctor(DataBinderOptions opts, ReadOnlyCollection`1 physicalSchema, ReadOnlyCollection`1 logicalSchema)
   at Sylvan.Data.CompiledBinderCache`1.<>c__DisplayClass1_0.<GetBinder>b__0(SchemaKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Sylvan.Data.DataExtensions.<GetRecords>d__4`1.MoveNext()
   at Cast3.Job.Metadata.Import.Services.MetadataService.GetExcelDateDto(String sourceFilePath) in C:\Users\p0104651\source\repos\Cast3\customer\cast-metadata-import-job\src\Services\MetadataService.cs:line 114

  This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException<T>(T)
    System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey, TValue, System.Collections.Generic.InsertionBehavior)
    System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey, TValue)
    System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(System.Collections.Generic.List<TSource>, System.Func<TSource, TKey>, System.Func<TSource, TElement>, System.Collections.Generic.IEqualityComparer<TKey>)
    System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TKey>, System.Func<TSource, TElement>, System.Collections.Generic.IEqualityComparer<TKey>)
    Sylvan.Data.CompiledDataBinder<T>.CompiledDataBinder(Sylvan.Data.DataBinderOptions, System.Collections.ObjectModel.ReadOnlyCollection<System.Data.Common.DbColumn>, System.Collections.ObjectModel.ReadOnlyCollection<System.Data.Common.DbColumn>)
    Sylvan.Data.CompiledBinderCache<T>.GetBinder.AnonymousMethod__0(Sylvan.Data.SchemaKey)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey, System.Func<TKey, TValue>)
    Sylvan.Data.DataExtensions.GetRecords<T>(System.Data.Common.DbDataReader, Sylvan.Data.DataBinderOptions)
    Cast3.Job.Metadata.Import.Services.MetadataService.GetExcelDateDto(string) in MetadataService.cs

**Comment by darshana2000** [comment]
Thank you for the update. 
yes there are duplicated columns.
Yes please make the exceptions more meaningful.

BTW is there a setting which allow duplicated columns?
Can i do it via providing schema?

**Comment by darshana2000** [comment]
It would be great that if you could update an sample code for excel upload with a schma.
Thanks
