### ISSUE TITLE
Reading Records (binding) from an Excel that the table starts after the first line

### ISSUE THREAD

**Issue by ziongh** [MarkPflug/Sylvan.Data.Excel#184]
I have an Excel file that starts with some information on the first few rows, then there is a table that I want to parse.

I know that I could use the Read function to read cell by cell. But I'd like to use the Binder (GetRecords) on that part of the file.

I've tried to do a few ```edr.Read()``` to skip the first few rows and then use the GetRecords, but it fails.

Here is the code:
```csharp

await using var edr = await ExcelDataReader.CreateAsync(
	file.FileStream, 
	ExcelWorkbookType.ExcelXml, 
	new ExcelDataReaderOptions
	{
		Culture = CultureInfo.InvariantCulture,
	}, 
	cancellationToken);

edr.Read();
edr.Read();
edr.Read();

var binder = DataBinder.Create<TItemDefinition>(edr, new DataBinderOptions()
				               {
					               Culture = CultureInfo.InvariantCulture,
					               BindingMode = DataBindingMode.Any,
				               }); // <========== Throws Exception
```

The Exception is as Follows:
```
Sylvan.Data.UnboundMemberException: The data could not be bound to the target type, it either contains too many or to few columns. Specify a different BindingMode to allow binding a subset of columns or properties.
   at Sylvan.Data.CompiledDataBinder`1..ctor(DataBinderOptions opts, ReadOnlyCollection`1 physicalSchema, ReadOnlyCollection`1 logicalSchema)
   at Sylvan.Data.CompiledDataBinder`1..ctor(DataBinderOptions opts, ReadOnlyCollection`1 physicalSchema)
   at Sylvan.Data.CompiledBinderCache`1.<>c__DisplayClass1_0.<GetBinder>b__0(SchemaKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Sylvan.Data.CompiledBinderCache`1.GetBinder(DbDataReader reader, DataBinderOptions opts)
   at Sylvan.Data.DataBinder.Create[T](IDataReader reader, DataBinderOptions opts)
```

**Comment by MarkPflug** [comment]
You need to call `Initialize` when you find the header row. Initialize is implicitly called when you call Create to use the first row in the file as headers, and that row will continue to be the header row unless you call initialize yourself.

```C#
using Sylvan.Data;
using Sylvan.Data.Excel;

using var r = ExcelDataReader.Create("data.xlsx");

r.Read();
r.Read();
r.Read();

// use the current row of data as headers
r.Initialize();

var records = r.GetRecords<Record>().ToList();

public class Record {
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime Date { get; set; }
}

```
