### ISSUE TITLE
Binder Issue

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#51]
Ok after long time of no hearing from me i have an issue with Binder. 

In binding I assign column values to `string DateOfArrival_Str` and after function is used, only then I assign it to `DateTime DateOfArrival`, due to missmatches in date format, this way I can improve `.FixDateTime()` function. This proved to work on other files and classes also, but im getting errors on this file, not sure why. 

Binder seems to have issue with the first line as i tried to locate the issue. 
When i modify binder attached below to: 

_**Modified binder (seems to work on this issue, but it's slow)**_
```
        public static IEnumerable<T> GetList<T>(this DbDataReader reader)
        {
            var binder = DataBinder.Create<T>(reader);
            while (reader.Read())
            {
                var item = (T)Activator.CreateInstance(typeof(T));
                try
                {
                    binder.Bind(reader, item);
                }
                catch
                {
                    item = item;
                }
                yield return item;
            }
        }
```
It works, but drastically slows down, basically from what i could see in debugger item is somehow binded at the point of exception, but i cannot locate where the issue lies. 

**It's downloaded from sharepoint.**

Exception - DataBinder encountered an exception.
Inner - Specified cast is not valid.

   _at lambda_method21(Closure , DbDataReader , BinderContext , MDMMailRequest )
   at Infinity.extension_methods.SylvanExtension.GetList[T](DbDataReader reader)+MoveNext() in C:\Users\KRZMAS\Desktop\Projects\Infinity\Infinity_UAT\Infinity\extension methods\SylvanExtension.cs:line 23
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Infinity.main_functionalities.connections.excel.ExcelConnection.SylvanReader[T]() in C:\Users\KRZMAS\Desktop\Projects\Infinity\Infinity_UAT\Infinity\global functionalities\connections\excel\ExcelConnection.cs:line 114_

I downloaded data on both sheets _Sheet1_ & _out of MDC scope requests_

Both of them use different setup in **Extract Function** those are:

**_Sheet1_** 

- Setup.SheetName = "Sheet1"
- Setup.StartRow = 0
- Setup.JoinHeaders() = "RequestType,1,OperatingUnit,RequestNumber,RequestSystem,RequestorName,CompletedBy,DateOfArrival_Str,DateOfCompletion_Str,9,NumberOfRecords,Comment"// -> returns string 
- Setup.NeededHeaders() ->Returns array below.
![image](https://user-images.githubusercontent.com/87186377/166305137-23bd9cff-c19a-42ac-97ff-7526ce987c33.png)

**_out of MDC scope requests_**

- Setup.SheetName = "out of MDC scope requests"
- Setup.StartRow = 0
- Setup.JoinHeaders() = "RequestType,OperatingUnit,RequestNumber,RequestSystem,RequestorName,CompletedBy,DateOfArrival_Str,DateOfCompletion_Str,8,NumberOfRecords,RequestID,Comment,RequestorEmail"// -> returns string 
- Setup.NeededHeaders() ->Returns array below.
![image](https://user-images.githubusercontent.com/87186377/166305372-2649d891-b574-4871-b6b3-0c75c4bfb6a1.png)

**File:**
Sent on emial
 
**Standard Binder - Extension (this one i generally use)**
```
        public static IEnumerable<T> GetList<T>(this DbDataReader reader)
        {
            var binder = DataBinder.Create<T>(reader);
            while (reader.Read())
            {
                var item = (T)Activator.CreateInstance(typeof(T));
                binder.Bind(reader, item);
                yield return item;
            }
        }
```

**T - class**
```
    public class MDMMailRequest
    {
        public DateTime? DateOfArrival { get; set; }
        public DateTime? DateOfCompletion { get; set; }
        public int? ID { get; set; }
        public string? RequestType { get; set; }
        public string? OperatingUnit { get; set; }
        public string? RequestNumber { get; set; }
        public string? RequestSystem { get; set; }
        public string? RequestID { get; set; }
        public string? RequestorName { get; set; }
        public string? CompletedBy { get; set; }
        public string? DateOfArrival_Str
        {
            get { return DateOfArrival.ToString(); }
            set
            {
                DateOfArrival = value.FixDateTime();
            }
        }
        public string? DateOfCompletion_Str
        {
            get { return DateOfCompletion.ToString(); }
            set
            {
                DateOfCompletion = value.FixDateTime();
            }
        }
        public int? ProcessingTime { get; set; }
        public int? NumberOfRecords { get; set; }
        public string? Comment { get; set; }
        public string? RequestorEmail { get; set; }
        public bool OutOfScope { get; set; }
    }

```
**Extract Function**
```
        private List<T>? SylvanReader<T>()
        {
            try
            {
                //sylvan option, get error lines as null (example : 20202/02/02 will be extracted as null date)
                var options = new SylExcel.ExcelDataReaderOptions { Schema = SylExcel.ExcelSchema.Default, GetErrorAsNull = true };
                //collect data
                using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(Setup.FilePath, options))
                {
                    //loop to locate needed sheet from passed setup
                    if (!string.IsNullOrWhiteSpace(Setup.SheetName))
                    {
                        while (excelDataReader.WorksheetName != Setup.SheetName)
                        {
                            excelDataReader.NextResult();

                            if (excelDataReader.WorksheetName == null)
                            {
                                //throw exception, that sheet was not located
                                throw new Exception("didnt find the sheet");
                            }
                        }
                    }

                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines
                    for (int i = 0; i < Setup.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }
                    //get all coulmns in file to column specified as max
                    var schema = Schema.Parse(Setup.JoinHeaders());

                    excelDataReader.InitializeSchema(schema.GetColumnSchema(), useHeaders: true);

                    var dataReader = excelDataReader.Select(Setup.NeededHeaders());

                    var binderOptions = new DataBinderOptions
                    {
                        InferColumnTypeFromMember = true,
                        BindingMode = DataBindingMode.Any
                    };
                    DataBinder.Create<T>(dataReader, binderOptions);

                    return dataReader.GetList<T>().ToList();
                }
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
```

**Date handler function for T class**
```
        public static DateTime? FixDateTime(this string? _string)
        {
            DateTime test;

            if (string.IsNullOrWhiteSpace(_string)) return null;
            //initial parse
            if (DateTime.TryParse(_string, out test)) return test;

            _string = _string.Trim();   

            //remove additional spaces
            if (_string.Contains("  "))
            {
                _string = _string.Replace("  ", " ");
            }

            //test 1
            if(DateTime.TryParse(_string, out test)) return test;


            //luke format is "-", change it to needed date
            if (_string.Contains("-"))
            {
                try
                {
                    int len = _string.Length;
                    int year = int.Parse(_string.Substring(7, 4));
                    int month = int.Parse(_string.Substring(4, 2));
                    int day = int.Parse(_string.Substring(1, 2));
                    int hour = int.Parse(_string.Substring(12, 2));
                    int minute = int.Parse(_string.Substring(15, 2));
                    int second = len > 17 ? int.Parse(_string.Substring(18, 2)) :  0;
                    test = new DateTime(year: year, month: month, day: day, hour: hour, minute: minute, second: second);
                    return test;
                }
                catch
                {
                    return null;
                }
            }

            //sale force format
            if (_string.Contains(",") && _string.Contains("."))
            {
                _string = _string.Replace(",", "");

                try
                {
                    int len = _string.Length;
                    int year = int.Parse(_string.Substring(7, 4));
                    int month = int.Parse(_string.Substring(4, 2));
                    int day = int.Parse(_string.Substring(1, 2));
                    int hour = int.Parse(_string.Substring(12, 2));
                    int minute = int.Parse(_string.Substring(15, 2));
                    int second = len > 17 ? int.Parse(_string.Substring(18, 2)) : 0;
                    test = new DateTime(year: year, month: month, day: day, hour: hour, minute: minute, second: second);
                    return test;
                }
                catch
                {
                    return null;
                }
            }

            return null;

        }
```

Quite lengthy, I saw that you are scares of time, so i'll try to find the issue myself to best of my ability. Let me know if there is somehting i might have missed.

**Comment by KMastalerz** [comment]
Hello Mark, 

Yes i decided that handling exceptions is quite risky, the 1st encountered issue is on 1st line with data in file. 

![image](https://user-images.githubusercontent.com/87186377/167772078-62ad865f-cb55-42df-9125-8fbeaf0b1dc9.png)

![image](https://user-images.githubusercontent.com/87186377/167772185-4bfb1352-2d6b-436b-b07b-ebacb9f3d7fd.png)

![image](https://user-images.githubusercontent.com/87186377/167772381-f2263b03-7ef4-4ec9-a697-ab8425f26d08.png)

OR  (Im not sure if it's referencing Column Ordinal or BaseColumn Ordinal)

![image](https://user-images.githubusercontent.com/87186377/167773368-5131e681-f079-4849-a5f5-759de4955416.png)

So the address of exception would be: 
Sheet: _"Sheet1"_
Cell : _"I2"_ or _"K2"_

For this test i didn't change enything but T-class: 

```
    public class MDMMailRequest : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }

        private DateTime? _DateOfArrival;
        private DateTime? _DateOfCompletion;
        private int? _ID;
        private string? _RequestType;
        private string? _OperatingUnit;
        private string? _RequestNumber;
        private string? _RequestSystem;
        private string? _RequestID;
        private string? _RequestorName;
        private string? _CompletedBy;
        private int? _ProcessingTime;
        private int? _NumberOfRecords;
        private string? _Comment;
        private string? _RequestorEmail;
        private bool _OutOfScope;
        private string _InsertedBy;
        private DateTime _InsertedDate;



        public DateTime? DateOfArrival 
        {
            get { return _DateOfArrival; }
            set
            {
                _DateOfArrival = value;
                OnPropertyChanged("DateOfArrival");
            }
        }
        public DateTime? DateOfCompletion
        {
            get { return _DateOfCompletion; }
            set
            {
                _DateOfCompletion = value;
                OnPropertyChanged("DateOfCompletion");
            }
        }
        public int? ID
        {
            get { return _ID; }
            set
            {
                _ID = value;
                OnPropertyChanged("ID");
            }
        }
        public string? RequestType
        {
            get { return _RequestType; }
            set
            {
                _RequestType = value;
                OnPropertyChanged("RequestType");
            }
        }
        public string? OperatingUnit
        {
            get { return _OperatingUnit; }
            set
            {
                _OperatingUnit = value;
                OnPropertyChanged("OperatingUnit");
            }
        }
        public string? RequestNumber
        {
            get { return _RequestNumber; }
            set
            {
                _RequestNumber = value;
                OnPropertyChanged("RequestNumber");
            }
        }
        public string? RequestSystem
        {
            get { return _RequestSystem; }
            set
            {
                _RequestSystem = value;
                OnPropertyChanged("RequestSystem");
            }
        }
        public string? RequestID
        {
            get { return _RequestID; }
            set
            {
                _RequestID = value;
                OnPropertyChanged("RequestID");
            }
        }
        public string? RequestorName
        {
            get { return _RequestorName; }
            set
            {
                _RequestorName = value;
                OnPropertyChanged("RequestorName");
            }
        }
        public string? CompletedBy
        {
            get { return _CompletedBy; }
            set
            {
                _CompletedBy = value;
                OnPropertyChanged("CompletedBy");
            }
        }
        public int? ProcessingTime
        {
            get { return _ProcessingTime; }
            set
            {
                _ProcessingTime = value;
                OnPropertyChanged("ProcessingTime");
            }
        }
        public int? NumberOfRecords
        {
            get { return _NumberOfRecords; }
            set
            {
                _NumberOfRecords = value;
                OnPropertyChanged("NumberOfRecords");
            }
        }
        public string? Comment
        {
            get { return _Comment; }
            set
            {
                _Comment = value;
                OnPropertyChanged("Comment");
            }
        }
        public string? RequestorEmail
        {
            get { return _RequestorEmail; }
            set
            {
                _RequestorEmail = value;
                OnPropertyChanged("RequestorEmail");
            }
        }
        public bool OutOfScope
        {
            get { return _OutOfScope; }
            set
            {
                _OutOfScope = value;
                OnPropertyChanged("OutOfScope");
            }
        }
        public string? InsertedBy
        {
            get { return _InsertedBy; }
            set
            {
                _InsertedBy = value;
                OnPropertyChanged("InsertedBy");
            }
        }
        public DateTime InsertedDate
        {
            get { return _InsertedDate; }
            set
            {
                _InsertedDate = value;
                OnPropertyChanged("InsertedDate");
            }
        }
        public string? DateOfArrival_Str
        {
            get { return DateOfArrival.ToString(); }
            set
            {
                DateOfArrival = value.FixDateTime();
                OnPropertyChanged("DateOfArrival_Str");
            }
        }
        public string? DateOfCompletion_Str
        {
            get { return DateOfCompletion.ToString(); }
            set
            {
                DateOfCompletion = value.FixDateTime();
                OnPropertyChanged("DateOfCompletion_Str");
            }
        }
    }
```

**Comment by MarkPflug** [comment]
I can't reproduce this. I wrote a test that binds empty fields to an `int?` and it works just fine. If you have non-numeric characters it is going to fail though.

**Comment by KMastalerz** [comment]
[](url)

**Comment by KMastalerz** [comment]
[MDM Statistics - Mailbox Template.zip](https://github.com/MarkPflug/Sylvan.Data.Excel/files/8682384/MDM.Statistics.-.Mailbox.Template.zip)

Try this with same code as above column _**L**_ empty and represented as `int?` in T-class

Setup.JoinHeaders() returns - 
"OutOfScope,RequestType,OperatingUnit,RequestNumber,RequestSystem,RequestID,RequestorName,RequestorEmail,CompletedBy,DateOfArrival,DateOfCompletion,NumberOfRecords,Comment"

Setup.NeededHeaders() returns -
![image](https://user-images.githubusercontent.com/87186377/168163336-7f8333b5-def3-4ebf-a398-c58a21975eda.png)

Sheet - Template

**Comment by KMastalerz** [comment]
I have again similar issue, with file :
[BW Cloud - Copy.xlsx](https://github.com/MarkPflug/Sylvan.Data.Excel/files/8825710/BW.Cloud.-.Copy.xlsx)
When i try to bind value from Q2 to "decimal?" i am getting an Binder Issue
